version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  backend:install:
    desc: Instala dependencias backend con Poetry
    dir: backend
    cmds:
      - poetry install

  backend:run:
    desc: Ejecuta FastAPI con autoreload
    dir: backend
    deps: [backend:install]
    cmds:
      - poetry run uvicorn app.main:app --reload

  frontend:dev:
    desc: Ejecuta Vite dev server
    dir: frontend
    cmds:
      - npm run dev -- --host

  fmt:
    desc: Formatea Python con black y JS/TS con prettier (si los tienes instalados)
    cmds:
      - echo "🔧 Formatting backend..."
      - black backend || true
      - echo "🔧 Formatting frontend..."
      - prettier -w frontend || true
