version: '3'

tasks:
  # Backend tasks
  install-backend:
    desc: Install backend (Python) dependencies
    dir: backend
    cmds:
      - pip install -r requirements.txt

  run-backend:
    desc: Run backend in development mode
    dir: backend
    cmds:
      - uvicorn main:app --reload

  test-backend:
    desc: Run backend tests
    dir: backend
    cmds:
      - pytest

  # Frontend tasks
  install-frontend:
    desc: Install frontend (Svelte) dependencies
    dir: frontend
    cmds:
      - npm install

  run-frontend:
    desc: Run frontend in development mode
    dir: frontend
    cmds:
      - npm run dev

  build-frontend:
    desc: Build production frontend
    dir: frontend
    cmds:
      - npm run build

  test-frontend:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npm run test

  # Full project
  install:
    desc: Install both backend and frontend dependencies
    cmds:
      - task: install-backend
      - task: install-frontend

  dev:
    desc: Run backend and frontend in development mode (parallel)
    cmds:
      - task: run-backend &
      - task: run-frontend

  test:
    desc: Run backend and frontend tests
    cmds:
      - task: test-backend
      - task: test-frontend
