"""Add Google OAuth fields to User model

Revision ID: 2ccd6a394e78
Revises: 01_initial_migration
Create Date: 2025-04-20 15:14:07.615888

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ccd6a394e78"
down_revision = "01_initial_migration"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("google_access_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("google_refresh_token", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "user", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_column("user", "last_login")
    op.drop_column("user", "created_at")
    op.drop_column("user", "google_refresh_token")
    op.drop_column("user", "google_access_token")
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###
