"""Add Google avatar to User model

Revision ID: 65adc6e230bc
Revises: 2ccd6a394e78
Create Date: 2025-04-23 16:20:59.222197

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65adc6e230bc"
down_revision = "2ccd6a394e78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_avatar", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "google_avatar")
    # ### end Alembic commands ###
