"""create_user_plans_table

Revision ID: 852ed1f4d09e
Revises: e3e776686210
Create Date: 2025-04-26 18:18:16.000323

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "852ed1f4d09e"
down_revision = "e3e776686210"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_plans_id"), "user_plans", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_plans_user_id"), "user_plans", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_plans_user_id"), table_name="user_plans")
    op.drop_index(op.f("ix_user_plans_id"), table_name="user_plans")
    op.drop_table("user_plans")
    # ### end Alembic commands ###
