"""remove_prompt_templates_table

Revision ID: ccc318f08674
Revises: 623b6ced729a
Create Date: 2025-04-27 13:07:56.279385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc318f08674'
down_revision = '623b6ced729a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 