"""add user_plan table

Revision ID: d7cb9d4c3b7f
Revises: mergeprompts1
Create Date: 2025-04-26 12:56:32.190032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cb9d4c3b7f'
down_revision = 'mergeprompts1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 