"""implement_user_plans_table

Revision ID: e3e776686210
Revises: eb723f8b5486
Create Date: 2025-04-26 18:16:10.359058

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3e776686210"
down_revision = "eb723f8b5486"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
