"""add developer fields to user

Revision ID: eb723f8b5486
Revises: d7cb9d4c3b7f
Create Date: 2025-04-26 17:35:17.146433

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb723f8b5486"
down_revision = "d7cb9d4c3b7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_developer", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "dev_plan_active", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "dev_plan_active")
    op.drop_column("user", "is_developer")
    # ### end Alembic commands ###
