# Configuración básica de Jekyll
title: "LukaLibre Docs"
description: LukaLibre Docs
baseurl: "" # Para GitHub Pages, si tu sitio está en la raíz del repositorio
url: "https://lukalibre.org/" # Tu dominio

# Configuración del tema
remote_theme: just-the-docs/just-the-docs

# Configuración de Markdown y conversión
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Archivos y carpetas a excluir
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Configuración del layout por defecto
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Configuración de Just the Docs
aux_links:
  "LukaLibre en GitHub":
    - "//github.com/raestrada/lukalibre"

# Configuración de colores y logo
logo: "https://lukalibre.org/assets/images/lukalibre.png"
favicon_ico: "https://lukalibre.org/assets/images/lukalibre-notext.png"

# Colores de LukaLibre
color_scheme: "lukalibre"

# Configuración de búsqueda
search_enabled: true
search:
  placeholder: "Buscar en LukaLibre Docs..."
  button:
    label: "Buscar"
    icon: "search"

# Configuración de navegación
nav_external_links: true
nav_fold: true
nav_exclude: []
