# Configuración básica de Jekyll
title: "LukaLibre Docs"
description: LukaLibre Docs
baseurl: "" # Para GitHub Pages, si tu sitio está en la raíz del repositorio
url: "https://lukalibre.org/" # Tu dominio
remote_theme: just-the-docs/just-the-docs # Tema remoto Just the Docs

# Configuración de Markdown y conversión
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Archivos y carpetas a excluir
exclude:
  - Gemfile
  - Gemfile.lock

# Configuración del layout por defecto
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Configuración de colores y logo
logo: "/assets/images/lukalibre_logo.svg"
favicon_ico: "/assets/images/lukalibre-notext.png"

# Colores de LukaLibre
color_scheme: "lukalibre"
colors:
  primary:
    base: "#3A6351" # verde-luka
    text: "#F9F9F9" # blanco-panraza
  accent:
    base: "#FFC857" # amarillo-caleta
    text: "#222222" # negro-callado
  background:
    base: "#F9F9F9" # blanco-panraza
    text: "#222222" # negro-callado
  sidebar:
    base: "#D5E5D9" # verde-nube
    text: "#222222" # negro-callado
