name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install Poetry
        run: pip install poetry
        
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        
      - name: Run tests
        run: poetry run pytest tests/ --cov=app --cov-report=xml
        
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/python
            p/owasp-top-ten
            p/security-audit
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN || '' }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID || '' }}
